"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from examples.tenant_tutorial.tenant_tutorial.settings import TENANT_MODEL, SHARED_APPS
import os
import hashlib

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*(ml40emz9ky+080g2e#h!9$3vb5z28-95$#g=55$r9mz_xoc8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
# Shared apps and Tenant apps
SHARED_APPS = [
    # Shared core apps
    'django_tenants',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_yasg',
    'tenant',
]

# With Examples for migrations as i develop
TENANT_APPS = [
    # Apps that should have separate tables per tenant
    'django.contrib.contenttypes',  # For permissions
    'django.contrib.auth',  # Per-tenant users

    # Tenant-specific apps
    'user',
    #'projects',
    #'tasks',
]

# Rebuild INSTALLED_APPS
INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'config.middleware.TenantDatabaseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.APIKeyAuthenticationMiddleware',
    'config.middleware.TenantIsolationMiddleware'
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Dynamic database config
def get_databases():
    databases = {
        'default': {
            'ENGINE': 'django_tenants.postgresql_backend',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': 600,
            'ATOMIC_REQUESTS': True
        }
    }
    # Add tenant databases from environment or load dynamically
    # & will be added at runtime when tenants are created
    return databases

DATABASES = get_databases()

# Tenant settings
TENANT_MODEL = 'tenant.Tenant'
TENANT_DOMAIN_MODEL = 'tenant.Domain'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.CustomUser'

PASSWORD_HASHERS = [
    'users.hashers.Argon2TenantHasher',
    'users.hashers.BcryptTenantHasher',
    'users.hashers.ScryptTenantHasher',
    'users.hashers.PBKDF2TenantHasher',

    # Built-in fallback hashers
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contib.auth.hashers.Argon2PasswordHasher',
    'django.contib.auth.hashers.BcryptSHA256PasswordHasher',
    'django.contib.auth.hashers.ScryptPasswordHasher',
]
PASSWORD_HASHING_CONFIG = {
    'argon2': {
        'time_cost': 2,
        'memory_cost': 512,  # KB (not MB)
        'parallelism': 2,
        'hash_length': 16,
        'salt_length': 16,
    },
    'bcrypt': {
        'rounds': 12,
    },
    'scrypt': {
        'N': 16384,  # Memory cost
        'r': 8,      # Block size
        'p': 1,      # Parallelization
        'key_length': 32,
        'salt_length': 16,
    },
    'pbkdf2_sha256': {
        'iterations': 260000,
        'digest': 'sha256',
    },
}
# Password Policy Defaults
PASSWORD_MIN_LENGTH = 16
PASSWORD_MAX_LENGTH = 128
PASSWORD_REQUIRE_UPPERCASE = True
PASSWORD_REQUIRE_LOWERCASE = True
PASSWORD_REQUIRE_DIGITS = True
PASSWORD_REQUIRE_SPECIAL_CHARS = True
PASSWORD_HISTORY_SIZE = 5
PASSWORD_EXPIRY_DAYS = 90

# Account sec defaults
MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_DURATION_MINUTES = 30

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Database router
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
    'config.database_routers.HybridTenantRouter',
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
