# Generated by Django 6.0.1 on 2026-02-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                ("is_custom", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tenat_domains",
            },
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="company_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="tenant",
            name="auto_create_schema",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="auto_drop_schema",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="custom_domain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="database_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_projects",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_users",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free (Schema)"),
                    ("starter", "Starter (Schema)"),
                    ("professional", "Professional (Database)"),
                    ("enterprise", "Enterprise (Database)"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tenant_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard - Schema Isolation"),
                    ("premium", "Premium - Database Isolation"),
                    ("enterprise", "Enterprise - Database Isolation"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                    ("trial", "Trial"),
                    ("expired", "Expired"),
                ],
                default="trial",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["tenant_type", "status"], name="tenants_tenant__090e3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["plan", "status"], name="tenants_plan_6bb5bd_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="tenant",
            table="tenants",
        ),
        migrations.AddField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenant.tenant",
            ),
        ),
    ]
